### PR TITLE
 Update HTML and CSS.

### PR DESCRIPTION
**Pull request by emmanuelsteven**
My first HTML/CSS project in Microverse
- Updated the  README file to a professional standard.
- Updated both HTML and CSS files.

### CODE REVIEW

**Review by wayungi — CHANGES_REQUESTED** [review]
Hi @emmanuelsteven , 

Great job implementing the project thus far! 👏🏾 👏🏾 

image

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- [ ] All linter checks passing ✔️ 
- [ ] Good commit messages ✔️ 
- [ ] No merge conflicts ✔️ 
- [ ]  Correct GitHub flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._
- [ ] All projects should have a fully and professionally filled README file. Yours is blank. Please use [this template](https://github.com/microverseinc/readme-template) to fill in all sections of yours. Remember to delete the logo and all lines beginning with `>`  after your are done. 😆 

- [ OPTIONAL ]  The correct way to ignore the node_modules is like this `node_modules/` notice the forward slash at the end. 😄 
- [ ]  Please also write a descriptive PR body
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by emmanuelsteven** [comment]
Made necessary changes on the README file as per standard requirement

**Review by hiromataba — CHANGES_REQUESTED** [review]
Hi @emmanuelsteven 👋 👋 , 

almost-there

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- All linter checks passing ✔️
- Good commit messages ✔️
- No merge conflicts ✔️
- Correct GitHub flow 

 ## Required Changes ♻️
_Check the comments under the review._
- [ ]  Please fix the `MIT` link it is throwing an error when I click on it 

image

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by bimbolabuari — COMMENTED** [review]
Hello @emmanuelsteven 👋,

_This is an additional review as a result of the second opinion request._

- Kudos on working on this milestone and welcome to Microverse 👍 

   - I strongly suggest you implement the changes, this is to make your README file more descriptive and professional and also have a proper license for your project.
   - You can create a `LICENSE` file and personalise this[ template ](https://choosealicense.com/licenses/mit/) and add it to the file.

Keep rocking 🚀!

**Comment by emmanuelsteven** [comment]
okay thank you for taking the time to say this but I would be a lot more
comfortable if I were assured that is the only change there is to make. as
this is my last chance.

**Review by divinecharlotte — CHANGES_REQUESTED** [review]
Hi @emmanuelsteven 👋, 

## STATUS: REQUESTED CHANGES ♻️ 

Good job so far 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!


### To Highlight 🎯 💡 

- All linter checks passing ✔️
- Good commit messages ✔️
- No merge conflicts ✔️
- Correct GitHub flow

## Required Changes ♻️

- [ ] kindly fix the MIT link as requested by the previous reviewer it is still throwing an error when I click on it fixing it will make your Readme more professional

_Check the comments under the review._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Owusu-Desmond — APPROVED** [review]
Hi @emmanuelsteven , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
